FROM --platform=$BUILDPLATFORM rust:latest AS build

ARG TARGETARCH

RUN apt-get update && apt-get install -y git build-essential curl musl-tools

WORKDIR /root/shadowsocks-rust

ADD . .

RUN git clone https://github.com/shadowsocks/shadowsocks-rust.git && \
    cd shadowsocks-rust \
    rustup install "$(cat rust-toolchain)" && \
    case "$TARGETARCH" in \
    "386") \
        RUST_TARGET="i686-unknown-linux-musl" \
        MUSL="i686-linux-musl" \
        ;; \
    "amd64") \
        RUST_TARGET="x86_64-unknown-linux-musl" \
        MUSL="x86_64-linux-musl" \
        ;; \
    "arm64") \
        RUST_TARGET="aarch64-unknown-linux-musl" \
        MUSL="aarch64-linux-musl" \
        ;; \
    *) \
        echo "Doesn't support $TARGETARCH architecture" \
        exit 1 \
        ;; \
    esac && \
    wget -qO- "https://musl.cc/$MUSL-cross.tgz" | tar -xzC /root/ && \
    CC=/root/$MUSL-cross/bin/$MUSL-gcc && \
    rustup target add $RUST_TARGET && \
    RUSTFLAGS="-C linker=$CC" CC=$CC cargo build --target $RUST_TARGET --release && \ 
    mv target/$RUST_TARGET/release/ss* target/release/ && \
    wget https://github.com/shadowsocks/v2ray-plugin/releases/download/v1.3.1/v2ray-plugin-linux-amd64-v1.3.1.tar.gz && \
    tar -xvf v2ray-plugin-linux-amd64-v1.3.1.tar.gz && \
    mv v2ray-plugin_linux_amd64  target/release/v2ray-plugin  
    


FROM alpine:latest AS ssserver

LABEL maintainer="cx@tinyserve.com"


COPY --from=build /root/shadowsocks-rust/shadowsocks-rust/target/release/ssserver /usr/bin

COPY --from=build /root/shadowsocks-rust/shadowsocks-rust/target/release/v2ray-plugin /usr/bin


COPY --from=build /root/shadowsocks-rust/shadowsocks-rust/examples/config.json /etc/shadowsocks-rust/

ENTRYPOINT [ "ssserver", "--log-without-time", "-c", "/etc/shadowsocks-rust/config.json" ]
